# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
    color: #00008b
  - name: Teaching
    url: "/#features"
    weight: 11
    color: #00008b
  - name: Publications
    url: "/#publications"
    weight: 12
    color: #00008b
  - name: Film
    url: "/#film"
    weight: 13
    color: #00008b
  - name: 
    url: 
    weight: 20
  - name:
    url:
    weight: 30
  - name:
    url:
    weight: 40
